# Project information
site_name: HUG AI DEV
site_url: https://hugai.dev
site_author: Sebastian Larrauri
site_description: >-
  "We don’t automate developers — we multiply them."

# Repository
repo_name: hugaidev/ai-development
repo_url: https://github.com/hugaidev/ai-development

copyright: Copyright &copy; 2024 - 2025 Sebastian Larrauri - Creative Commons Atribución 4.0 Internacional (CC BY 4.0)
docs_dir: docs
# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
  # --- CONTENIDO ---
  - content.code.annotate           # ✅ Permite anotar y numerar líneas de código
  - content.code.copy               # ✅ Botón para copiar código
  - content.code.select             # 🔒 Selección dentro de bloques de código (raro de usar)
  # - content.action.edit           # 🔒 Botón para editar la página en GitHub
  # - content.action.view           # 🔒 Botón para ver fuente en el repo
  - content.footnote.tooltips       # 🔒 Convierte notas al pie en tooltips
  - content.tabs.link             # 🔒 Tabs con enlaces individuales (si usás tabs complejas)
  - content.tooltips                # ✅ Muestra tooltips para enlaces con título

  # --- NAVEGACIÓN ---
  - navigation.tabs                 # ✅ Tabs superiores (para separar secciones como AISDG / Agents)
  - navigation.tabs.sticky        # 🔒 Tabs siempre visibles al hacer scroll (no necesario aún)
  - navigation.footer               # ✅ Enlaces prev/next al pie
  - navigation.tracking             # ✅ Actualiza URL según sección visible
  - navigation.indexes              # ✅ index.md como portada de subcarpetas
  # - navigation.expand             # 🔒 Expande todo el menú (innecesario por ahora)
  # - navigation.instant            # 🔒 Navegación instantánea sin recarga (incompatible con algunos scripts)
  # - navigation.instant.prefetch   # 🔒 Precarga páginas al hacer hover (más útil en sitios grandes)
  # - navigation.instant.progress   # 🔒 Barra de carga para navegación instantánea
  # - navigation.prune              # 🔒 Oculta entradas muy profundas automáticamente
  - navigation.sections           # 🔒 Agrupa el menú lateral por secciones (útil si hay cientos de páginas)

  # --- BÚSQUEDA ---
  - search.highlight                # ✅ Resalta palabras en los resultados
  - search.suggest                  # ✅ Sugerencias mientras escribís
  - search.share                    # ✅ Permite compartir búsqueda con URL

  # --- TOC (Índice) ---
  # - toc.integrate                   # ✅ Muestra tabla de contenidos dentro del contenido
  # - toc.follow                    # 🔒 Hace que el índice siga tu scroll (no necesario si se integra)

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg

# Plugins
plugins:
  # - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - social
  - tags

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hugaidev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/hugaidev
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/hugaidev

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  docs/blog/draft/*.md

# Page tree
nav:
  - Home: index.md
  - Methodology:
    - Introduction: methodology/index.md
    - Core Principles: methodology/core-principles.md
    - AI Design Patterns: methodology/ai-design-patterns.md
    - Governance and Ethics: methodology/governance-and-ethics.md
    - Development Lifecycle: methodology/development-lifecycle.md
    - Planning & Requirements: methodology/planning-requirements.md
    - Design & Architecture: methodology/design-architecture.md
    - Implementation: methodology/implementation.md
    - Testing & Quality Assurance: methodology/testing-quality-assurance.md
    - Deployment: methodology/deployment.md
    - Maintenance: methodology/maintenance.md
    - Governance & Monitoring: methodology/governance-monitoring.md
    - Metrics & KPIs: methodology/metrics.md
    - Human Checkpoints: methodology/checkpoints.md
    - Automated Gates: methodology/automated-gates.md
    - Best Practices & Pitfalls: methodology/best-practices-pitfalls.md
    
  - Agents:
    - Agents Introduction: agents/index.md
    - Architecture Agent: agents/architecture-agent.md
    - Branch/PR Manager Agent: agents/branch-pr-manager-agent.md
    - Compliance Agent: agents/compliance-agent.md
    - Deployment Agent: agents/deployment-agent.md
    - DevOps Agent: agents/devops-agent.md
    - Documentation Writer Agent: agents/documentation-writer-agent.md
    - Domain Expert Agent: agents/domain-expert-agent.md
    - Implementation Agent: agents/implementation-agent.md
    - Integration Agent: agents/integration-agent.md
    - Internal Reviewer Agent: agents/internal-reviewer-agent.md
    - Knowledge-Base Manager Agent: agents/knowledge-base-manager-agent.md
    - Maintenance Agent: agents/maintenance-agent.md
    - Observability Agent: agents/observability-agent.md
    - Performance Agent: agents/performance-agent.md
    - Prompt Refiner Agent: agents/prompt-refiner-agent.md
    - Requirements Analyzer Agent: agents/requirements-analyzer-agent.md
    - Retry Agent: agents/retry-agent.md
    - Risk Management Agent: agents/risk-management-agent.md
    - Router Agent: agents/router-agent.md
    - Security Agent: agents/security-agent.md
    - Test Agent: agents/test-agent.md
    - Escalation Manager Agent: agents/escalation-manager-agent.md

  - Tools:
    - Overview: tools/index.md
    - Base Infrastructure:
      - Version Control & Branching: tools/version-control.md
      - Code Search & RAG: tools/code-search.md
      - Containerization: tools/containerization.md
      - CI/CD Pipelines: tools/cicd-pipelines.md
    - AI Platform:
      - LLM-Powered Agents: tools/llm-agents.md
      - Workflow Orchestrator: tools/workflow-orchestrator.md
      - Context Store: tools/context-store.md
      - Automated Validation: tools/automated-validation.md
    - Quality & Security:
      - Static Analysis: tools/static-analysis.md
      - Test Automation: tools/test-automation.md
      - Security Scanning: tools/security-scanning.md
      - Performance Monitoring: tools/performance-monitoring.md
    - Operations:
      - Observability Stack: tools/observability-stack.md
      - Feature Flags: tools/feature-flags.md
      - Deployment Tools: tools/deployment-tools.md

  
  - Integration:
    - Agent Workflows: integration/agent-workflows.md
    - Tool Dependencies: integration/tool-dependencies.md
    - Lifecycle Gates: integration/lifecycle-gates.md
    
  - Guides:
    - Custom Agent Creation: guides/custom-agent-creation.md
    - Tool Integration: guides/tool-integration.md
    - Lifecycle Customization: guides/lifecycle-customization.md
    - Troubleshooting: guides/troubleshooting.md
    
  - Reference:
    - Configuration Reference: reference/configuration-reference.md
    
  - LLMs:
    - Model Configuration: llms/model-llm.md
    
  - Case Studies:
    - Overview: case-studies/index.md
    - Enterprise Modernization: case-studies/enterprise-modernization.md
    - Enterprise Transformation: case-studies/enterprise-transformation.md
    - Government Integration: case-studies/government-integration.md
    - Open Source Revitalization: case-studies/open-source-revitalization.md
    - Startup Development: case-studies/startup-development.md
  
  


