metadata:
  name: compliance-agent-configuration
  version: 1.0.0
  description: "AI agent specialized in regulatory compliance, data governance, and legal requirement validation for HUGAI applications"
  category: specialized-agents
  dependencies:
    - llm-models
    - compliance-frameworks
    - audit-tools
    - governance-systems
  tags:
    - compliance
    - governance
    - regulatory
    - audit
    - legal-requirements

configuration:
  # Compliance Agent Philosophy
  agent_philosophy:
    purpose: "Ensure HUGAI systems meet all applicable regulatory, legal, and organizational compliance requirements through continuous monitoring and validation"
    principles:
      proactive_compliance: "Identify and address compliance issues before they become violations"
      comprehensive_coverage: "Monitor compliance across all applicable regulations and standards"
      evidence_based_assurance: "Maintain auditable evidence of compliance activities"
      risk_based_approach: "Prioritize compliance efforts based on risk assessment"
      continuous_monitoring: "Implement ongoing compliance validation rather than point-in-time assessments"

  # Core Capabilities
  core_capabilities:
    regulatory_compliance:
      data_protection_regulations:
        gdpr:
          scope: "EU data subjects"
          key_requirements:
            - "lawful_basis_for_processing"
            - "data_subject_consent_management"
            - "right_to_be_forgotten"
            - "data_portability"
            - "privacy_by_design"
            - "data_protection_impact_assessments"
            - "breach_notification_requirements"
          
          monitoring_areas:
            - "personal_data_collection_practices"
            - "consent_management_systems"
            - "data_retention_policies"
            - "cross_border_data_transfers"
            - "vendor_data_processing_agreements"
        
        ccpa:
          scope: "California residents"
          key_requirements:
            - "consumer_right_to_know"
            - "consumer_right_to_delete"
            - "consumer_right_to_opt_out"
            - "non_discrimination_provisions"
            - "privacy_policy_requirements"
          
          monitoring_areas:
            - "consumer_request_handling"
            - "opt_out_mechanisms"
            - "privacy_policy_compliance"
            - "data_selling_disclosures"
        
        hipaa:
          scope: "Protected health information"
          key_requirements:
            - "administrative_safeguards"
            - "physical_safeguards"
            - "technical_safeguards"
            - "breach_notification_rule"
            - "minimum_necessary_standard"
          
          monitoring_areas:
            - "access_controls"
            - "audit_logs"
            - "encryption_requirements"
            - "business_associate_agreements"
      
      industry_standards:
        iso_27001:
          focus: "Information security management"
          controls:
            - "information_security_policies"
            - "organization_of_information_security"
            - "human_resource_security"
            - "asset_management"
            - "access_control"
            - "cryptography"
            - "physical_and_environmental_security"
            - "operations_security"
            - "communications_security"
            - "system_acquisition_development_maintenance"
            - "supplier_relationships"
            - "information_security_incident_management"
            - "information_security_in_business_continuity"
            - "compliance"
        
        soc_2:
          focus: "Service organization controls"
          trust_criteria:
            - "security"
            - "availability"
            - "processing_integrity"
            - "confidentiality"
            - "privacy"
        
        pci_dss:
          focus: "Payment card data security"
          requirements:
            - "firewall_configuration"
            - "password_management"
            - "cardholder_data_protection"
            - "encrypted_transmission"
            - "antivirus_usage"
            - "secure_systems_development"
            - "access_restriction"
            - "unique_user_identification"
            - "physical_access_restriction"
            - "network_monitoring"
            - "security_testing"
            - "information_security_policy"
    
    governance_capabilities:
      data_governance:
        data_classification:
          - "public_data"
          - "internal_data"
          - "confidential_data"
          - "restricted_data"
          - "personal_data"
          - "sensitive_personal_data"
        
        data_lifecycle_management:
          - "data_creation_governance"
          - "data_storage_governance"
          - "data_usage_governance"
          - "data_sharing_governance"
          - "data_retention_governance"
          - "data_disposal_governance"
        
        data_quality_assurance:
          - "data_accuracy_validation"
          - "data_completeness_checks"
          - "data_consistency_monitoring"
          - "data_timeliness_assessment"
          - "data_validity_verification"
      
      ai_governance:
        ai_ethics_compliance:
          - "algorithmic_fairness_assessment"
          - "bias_detection_and_mitigation"
          - "transparency_requirements"
          - "explainability_standards"
          - "human_oversight_validation"
        
        ai_model_governance:
          - "model_development_oversight"
          - "model_validation_requirements"
          - "model_deployment_controls"
          - "model_monitoring_standards"
          - "model_retirement_procedures"

  # Agent Configuration
  agent_configuration:
    model_selection:
      primary_model: "gpt-4"
      fallback_models: ["claude-3-5-sonnet", "gpt-4-turbo"]
      
      task_specific_models:
        regulatory_analysis: "gpt-4"
        risk_assessment: "claude-3-5-sonnet"
        policy_generation: "gpt-4-turbo"
        audit_reporting: "claude-3-haiku"
    
    operational_parameters:
      compliance_check_frequency: "daily"
      risk_assessment_interval: "weekly"
      audit_preparation_timeline: "monthly"
      
      human_escalation_triggers:
        - "regulatory_violation_detected"
        - "high_risk_compliance_gap_identified"
        - "audit_preparation_required"
        - "legal_interpretation_needed"
        - "policy_conflict_detected"
    
    integration_points:
      governance_platforms:
        - "collibra"
        - "informatica_axon"
        - "alation"
        - "apache_atlas"
      
      compliance_tools:
        - "riskonnect"
        - "metricstream"
        - "servicenow_grc"
        - "rsam"
      
      audit_platforms:
        - "workiva"
        - "auditboard"
        - "logicgate"
        - "processgene"

  # Compliance Workflows
  compliance_workflows:
    regulatory_assessment:
      workflow_name: "comprehensive_regulatory_compliance_assessment"
      
      steps:
        regulation_identification:
          description: "Identify applicable regulations and standards"
          actions:
            - "analyze_business_operations"
            - "identify_data_types_processed"
            - "determine_geographic_scope"
            - "assess_industry_requirements"
          
          deliverables:
            - "applicable_regulations_matrix"
            - "compliance_requirements_catalog"
            - "risk_exposure_assessment"
        
        gap_analysis:
          description: "Assess current compliance posture against requirements"
          depends_on: ["regulation_identification"]
          
          actions:
            - "review_current_policies_procedures"
            - "assess_technical_controls"
            - "evaluate_organizational_controls"
            - "identify_compliance_gaps"
          
          analysis_methods:
            - "control_maturity_assessment"
            - "risk_impact_analysis"
            - "evidence_gap_identification"
            - "remediation_priority_scoring"
        
        remediation_planning:
          description: "Develop compliance remediation roadmap"
          depends_on: ["gap_analysis"]
          
          actions:
            - "prioritize_remediation_activities"
            - "estimate_implementation_effort"
            - "define_success_metrics"
            - "create_implementation_timeline"
          
          deliverables:
            - "remediation_roadmap"
            - "resource_requirements_plan"
            - "compliance_project_charter"
            - "risk_mitigation_strategy"
        
        implementation_monitoring:
          description: "Monitor and validate remediation implementation"
          depends_on: ["remediation_planning"]
          
          actions:
            - "track_implementation_progress"
            - "validate_control_effectiveness"
            - "update_compliance_status"
            - "prepare_compliance_reports"
    
    continuous_monitoring:
      workflow_name: "ongoing_compliance_monitoring"
      
      monitoring_frequency: "real_time"
      
      monitoring_aspects:
        - "data_processing_activities"
        - "access_control_effectiveness"
        - "policy_adherence"
        - "regulatory_change_tracking"
        - "incident_compliance_impact"
      
      alert_conditions:
        critical:
          - "potential_regulatory_violation"
          - "data_breach_incident"
          - "unauthorized_data_access"
          - "policy_violation_detected"
        
        warning:
          - "compliance_drift_detected"
          - "policy_update_required"
          - "training_compliance_gap"
          - "vendor_compliance_risk"

  # Risk Assessment Framework
  risk_assessment:
    compliance_risk_categories:
      regulatory_risk:
        risk_factors:
          - "regulatory_change_frequency"
          - "penalty_severity"
          - "enforcement_likelihood"
          - "regulatory_scrutiny_level"
        
        assessment_criteria:
          - "current_compliance_maturity"
          - "control_effectiveness"
          - "historical_violation_patterns"
          - "industry_enforcement_trends"
      
      operational_risk:
        risk_factors:
          - "process_complexity"
          - "human_error_probability"
          - "system_reliability"
          - "third_party_dependencies"
        
        mitigation_strategies:
          - "process_automation"
          - "training_programs"
          - "redundancy_implementation"
          - "vendor_management"
      
      reputational_risk:
        risk_factors:
          - "public_visibility"
          - "stakeholder_expectations"
          - "media_attention_likelihood"
          - "competitive_implications"
    
    risk_scoring_methodology:
      impact_assessment:
        financial_impact:
          low: "< $100K"
          medium: "$100K - $1M"
          high: "$1M - $10M"
          critical: "> $10M"
        
        reputational_impact:
          low: "minimal_stakeholder_concern"
          medium: "moderate_public_attention"
          high: "significant_reputational_damage"
          critical: "severe_brand_impact"
      
      likelihood_assessment:
        very_low: "< 5%"
        low: "5% - 25%"
        medium: "25% - 50%"
        high: "50% - 75%"
        very_high: "> 75%"

  # Policy Management
  policy_management:
    policy_development:
      policy_categories:
        - "data_protection_policies"
        - "information_security_policies"
        - "ai_governance_policies"
        - "vendor_management_policies"
        - "incident_response_policies"
        - "business_continuity_policies"
      
      policy_lifecycle:
        development:
          - "regulatory_requirement_analysis"
          - "stakeholder_consultation"
          - "risk_assessment_integration"
          - "legal_review"
        
        approval:
          - "executive_review"
          - "legal_approval"
          - "stakeholder_sign_off"
          - "board_ratification"
        
        implementation:
          - "communication_planning"
          - "training_development"
          - "process_integration"
          - "system_configuration"
        
        monitoring:
          - "compliance_tracking"
          - "effectiveness_measurement"
          - "gap_identification"
          - "continuous_improvement"
    
    policy_maintenance:
      review_triggers:
        - "regulatory_changes"
        - "business_changes"
        - "risk_profile_changes"
        - "incident_learnings"
        - "scheduled_reviews"
      
      update_process:
        - "impact_assessment"
        - "stakeholder_consultation"
        - "change_approval"
        - "communication_rollout"
        - "training_updates"

integration:
  # Business Process Integration
  business_integration:
    development_lifecycle:
      requirements_phase:
        - "regulatory_requirement_identification"
        - "compliance_impact_assessment"
        - "privacy_impact_assessment"
      
      design_phase:
        - "privacy_by_design_validation"
        - "security_by_design_verification"
        - "compliance_architecture_review"
      
      implementation_phase:
        - "secure_coding_compliance"
        - "data_protection_implementation"
        - "access_control_configuration"
      
      deployment_phase:
        - "compliance_readiness_assessment"
        - "security_configuration_validation"
        - "audit_trail_enablement"
    
    operational_processes:
      incident_management:
        - "compliance_impact_assessment"
        - "regulatory_notification_requirements"
        - "remediation_compliance_validation"
      
      change_management:
        - "compliance_impact_analysis"
        - "regulatory_approval_requirements"
        - "policy_update_triggers"

  # Audit and Reporting Integration
  audit_integration:
    audit_preparation:
      evidence_collection:
        - "automated_evidence_gathering"
        - "documentation_consolidation"
        - "gap_remediation_tracking"
        - "control_testing_results"
      
      audit_response:
        - "auditor_request_management"
        - "evidence_presentation"
        - "finding_response_coordination"
        - "corrective_action_planning"
    
    reporting_automation:
      compliance_dashboards:
        - "regulatory_compliance_status"
        - "risk_exposure_metrics"
        - "policy_adherence_tracking"
        - "audit_readiness_indicators"
      
      regulatory_reporting:
        - "automated_report_generation"
        - "data_accuracy_validation"
        - "submission_timeline_management"
        - "regulatory_correspondence_tracking"

validation:
  # Compliance Agent Validation
  agent_effectiveness:
    compliance_detection_accuracy: ">95%"
    false_positive_rate: "<5%"
    regulatory_coverage_completeness: ">98%"
    audit_preparation_efficiency: ">90%"
  
  # Compliance Program Validation
  program_validation:
    regulatory_compliance_rate: ">99%"
    audit_finding_reduction: "measurable_improvement"
    policy_adherence_rate: ">95%"
    incident_compliance_response: "within_requirements"

examples:
  # GDPR Compliance Check Example
  gdpr_compliance_example:
    compliance_assessment: |
      ## GDPR Compliance Assessment
      
      ### Data Processing Activities Analysis
      - **Lawful Basis**: Article 6(1)(b) - Contract performance
      - **Data Categories**: Personal identifiers, contact information
      - **Processing Purpose**: User account management, service delivery
      - **Data Subjects**: EU residents using HUGAI platform
      
      ### Rights Management Implementation
      - **Right to Access**: ✅ Automated data export functionality
      - **Right to Rectification**: ✅ User profile update capabilities
      - **Right to Erasure**: ⚠️ Manual process, needs automation
      - **Data Portability**: ✅ JSON export format available
      
      ### Compliance Gaps Identified
      1. **High Priority**: Automate data erasure process (Art. 17)
      2. **Medium Priority**: Implement consent management system
      3. **Low Priority**: Enhance privacy policy clarity
      
      ### Recommendations
      1. Implement automated "Right to be Forgotten" workflow
      2. Deploy consent management platform
      3. Conduct privacy impact assessment for new features

# CLI Usage Examples
cli_usage: |
  # Initialize compliance agent
  hugai agent init compliance --regulations gdpr,ccpa,hipaa --frameworks iso27001,soc2
  
  # Run compliance assessment
  hugai agent compliance assess --scope full --regulations all --risk-analysis
  
  # Monitor compliance status
  hugai agent compliance monitor --real-time --alerts critical --dashboard executive
  
  # Generate compliance report
  hugai agent compliance report --period quarterly --format pdf --audience board
  
  # Prepare for audit
  hugai agent compliance audit-prep --auditor external --scope iso27001 --evidence-collection
  
  # Policy management
  hugai agent compliance policy update --trigger regulatory-change --review-cycle annual